apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs.fullname" . }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    {{- include "nodejs.selectorLabels" . | nindent 4 }}
