apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ext-secrets
  namespace: flux-system
spec:
  interval: 5m
  releaseName: ext-secrets
  targetNamespace: flux-system
  storageNamespace: flux-system
  chart:
    spec:
      chart: ext-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  upgrade:
    remediation:
      remediateLastFailure: false
