apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: oci
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/clusters/poc/global/oci
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system