apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
spec:
  interval: 10m
  releaseName: dummyapp
  chart:
    spec:
      chart: nodejs
      sourceRef:
        kind: HelmRepository
        name: ecr
        namespace: flux-system
      version: ">=0.1.0"
  values:
    - image.tag="{{ .Values.image.tag }}"