name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - qa
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t nodejs .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate tag based on branch
        id: generate-tag
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##*/} | tr / -)
          TAG_NAME="latest"
          
          if [ "$BRANCH_NAME" == "qa" ]; then
            # Fetch the last tag name, increment it
            LAST_TAG=$(git tag -l "qa-*" | sort -V | tail -n 1)
            TAG_NUMBER=${LAST_TAG#qa-}
            NEXT_TAG_NUMBER=$((TAG_NUMBER + 1))
            TAG_NAME="qa-$NEXT_TAG_NUMBER"
          elif [ "$BRANCH_NAME" == "prod" ]; then
            # Similar logic for prod tags
            LAST_TAG=$(git tag -l "prod-*" | sort -V | tail -n 1)
            TAG_NUMBER=${LAST_TAG#prod-}
            NEXT_TAG_NUMBER=$((TAG_NUMBER + 1))
            TAG_NAME="prod-$NEXT_TAG_NUMBER"
          fi
          
          echo "New tag: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Tag and push Docker image to Amazon ECR
        run: |
          docker tag nodejs:latest ${{ secrets.ECR_REGISTRY }}:${{ env.TAG_NAME }}
          docker push ${{ secrets.ECR_REGISTRY }}:${{ env.TAG_NAME }}

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions
